### ISSUE TITLE
Demo webpage not working with SD-1?

### ISSUE THREAD

**Issue by denjhang** [danielrfry/notesalad-editor#6]
https://danielrfry.github.io/notesalad-editor/
I found SD-1 is gray.

**Comment by danielrfry** [comment]
Currently a real SD-1 chip and MIDI interface is required to use the SD-1 mode, as there is no integrated emulator for that chip. Sorry for the confusion - I will try to add a note explaining this in the app. (#7)

If there is enough demand and I have time, I will release the design and code for the USB MIDI board used in the [demo video](https://youtu.be/qVMLqGQ5HB0) - however, it may be difficult to build as the SD-1 breakout board is unfortunately no longer available from Yamaha.
